# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Syncopated Pandemonium
tagline:             'Order & Chaos'
description:         'Hello There!'
url:                 http://www.aniket.ninja
baseurl:             'http://www.aniket.ninja'
paginate:            5

# About/contact
author:
  name:              Aniket Deole
  url:               twitter.com/AniketDeole
  email:             aniket [dot] deole @ gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
